### ISSUE TITLE
Download 404

### ISSUE THREAD

**Issue by willemeng** [MapIV/eagleye#102] opened 2022-03-07 01:36 UTC
HI, I got a 404 error when I downloaded the bag data and opened the website you provided.

**Comment by rsasaki0109** [comment] 2022-03-10 03:51
@kitsukawa 
Do you see what the problem is? Seems like a problem with your dropbox account.

**Comment by rsasaki0109** [comment] 2022-03-14 00:12
Sample data is shown below.
The develop branch has modified the link.
The master branch will reflect this April.

20200127 https://www.dropbox.com/s/pfs307qn7gfeou5/eagleye_sample_20200127.bag?dl=0
20200715 https://www.dropbox.com/s/w9ag6gs17bi80st/eagleye_sample_20200715.bag?dl=0

**Comment by rsasaki0109** [comment] 2022-03-24 23:47
I think we have solved the problem and will close this issue.
If you have any more problems, please submit an issue.

**Closed by rsasaki0109** 2022-03-24 23:47 UTC
